version: '3.8'

services:
  gluetun-health-check:
    build: .
    container_name: gluetun-health-check
    restart: unless-stopped
    volumes:
      # Required: Docker socket access for container management
      - /var/run/docker.sock:/var/run/docker.sock
      # Optional: If you need to access compose files from host
      # - /path/to/compose/files:/compose:ro
    environment:
      # All environment variables are OPTIONAL - app works with auto-discovery!
      # Health check interval in milliseconds (30 seconds default)
      - CHECK_INTERVAL=30000
      # Pattern to match Gluetun container images (default: gluetun)
      - GLUETUN_IMAGE_PATTERN=gluetun
      # Number of consecutive failures before redeployment (default: 2)
      - UNHEALTHY_THRESHOLD=2
      # Enable dry run mode for testing (default: false)
      - DRY_RUN=false
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    # Optional: Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 